export type WorkspaceRole = 'owner' | 'admin' | 'member' | 'viewer';

export const CAPABILITIES = {
  WORKSPACE_UPDATE: 'workspace:update',
  WORKSPACE_DELETE: 'workspace:delete',
  MEMBER_LIST: 'member:list',
  MEMBER_UPDATE: 'member:update',
  MEMBER_INVITE: 'member:invite',
  MEMBER_REMOVE: 'member:remove',
  INVITATION_LIST: 'invitation:list',
  INVITATION_CREATE: 'invitation:create',
  INVITATION_REVOKE: 'invitation:revoke',
  PAGE_VIEW: 'page:view',
  PAGE_CREATE: 'page:create',
  PAGE_UPDATE: 'page:update',
  PAGE_DELETE: 'page:delete',
} as const;

export type Capability = typeof CAPABILITIES[keyof typeof CAPABILITIES];

export const ROLE_CAPABILITIES: Record<WorkspaceRole, Capability[]> = {
  owner: [
    CAPABILITIES.WORKSPACE_UPDATE,
    CAPABILITIES.WORKSPACE_DELETE,
    CAPABILITIES.MEMBER_LIST,
    CAPABILITIES.MEMBER_UPDATE,
    CAPABILITIES.MEMBER_INVITE,
    CAPABILITIES.MEMBER_REMOVE,
    CAPABILITIES.INVITATION_LIST,
    CAPABILITIES.INVITATION_CREATE,
    CAPABILITIES.INVITATION_REVOKE,
    CAPABILITIES.PAGE_VIEW,
    CAPABILITIES.PAGE_CREATE,
    CAPABILITIES.PAGE_UPDATE,
    CAPABILITIES.PAGE_DELETE,
  ],
  admin: [
    CAPABILITIES.WORKSPACE_UPDATE,
    CAPABILITIES.MEMBER_LIST,
    CAPABILITIES.MEMBER_UPDATE,
    CAPABILITIES.MEMBER_INVITE,
    CAPABILITIES.MEMBER_REMOVE,
    CAPABILITIES.INVITATION_LIST,
    CAPABILITIES.INVITATION_CREATE,
    CAPABILITIES.INVITATION_REVOKE,
    CAPABILITIES.PAGE_VIEW,
    CAPABILITIES.PAGE_CREATE,
    CAPABILITIES.PAGE_UPDATE,
    CAPABILITIES.PAGE_DELETE,
  ],
  member: [
    CAPABILITIES.MEMBER_LIST,
    CAPABILITIES.INVITATION_LIST,
    CAPABILITIES.PAGE_VIEW,
    CAPABILITIES.PAGE_CREATE,
    CAPABILITIES.PAGE_UPDATE,
  ],
  viewer: [
    CAPABILITIES.MEMBER_LIST,
    CAPABILITIES.PAGE_VIEW,
  ]
};
